module.exports = function () {
  const areas = [
    'All',
    'Astoria',
    'Brooklyn',
    'Chelsea',
    'East Village',
    'Financial District',
    'Flatiron',
    'Gramercy',
    'Greenwich Village',
    'Harlem',
    "Hell's Kitchen",
    'Kips Bay',
    'Lower East Side',
    'Meatpacking District',
    'Midtown East',
    'Midtown West',
    'Murray Hill',
    'NoHo',
    'Nolita',
    'Park Slope',
    'Queens',
    'SoHo',
    'Theater District',
    'TriBeCa',
    'Union Square',
    'Upper East Side',
    'Upper West Side',
    'West Village',
    'Williamsburg',
  ];

  return areas;
};
